### ISSUE TITLE
How do I get the openings from the raw data?

### ISSUE THREAD

**Issue by Arthurfogo7** [atlasacademy/fgo-game-data-api#29]
I extracted the .apk and there was .bin and .bytes files there. So I want to know how can I extract them. For academic purposes.

**Comment by squaresmile** [comment]
Which opening are you looking for? Only the default one is in the apk iirc. Others are downloaded separately like this one: https://static.atlasacademy.io/JP/Movie/intro001.mp4

**Comment by Arthurfogo7** [comment]
I just wanted to know, how did you extract all this, mainly the videos, from the .apk file. For academic purposes.

**Comment by squaresmile** [comment]
I don't think the videos are encrypted at all. The video is in usm which can be extracted with https://github.com/donmai-me/WannaCRI or other USM tools.
For encrypted files, check out this repo: https://github.com/hexstr/FGOAssetsModifyTool
